name: deploy

on: [push, pull_request]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "run.sh"
          severity: "warning, error"
  
  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: deploy with sh script
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/IgorKha/Grafana-Mikrotik/master/run.sh)" ""
        
      - name: Test Grafana
        run: sleep 5 && curl -ILsS --retry 5 --retry-delay 2 "http://localhost:3000/login"

      - name: Test Prometheus
        run: curl -ILsS --retry 5 --retry-delay 2 "http://localhost:9090"
        
      - name: Test snmp_exporter
        run: curl -ILsS --retry 5 --retry-delay 2 "http://localhost:9116" 
        